# -*- coding: mbcs -*-
from part import *
from material import *
from section import *
from assembly import *
from interaction import *
from load import *
from mesh import *
from optimization import *
from job import *
from sketch import *
from visualization import *
from step import *
mdb.models.changeKey(fromName='Model-1', toName='guw_model')
mdb.models['guw_model'].ConstrainedSketch(name='__profile__', sheetSize=2.0)
mdb.models['guw_model'].sketches['__profile__'].rectangle(point1=(0, 0), 
    point2=(0.5, 0.5))
mdb.models['guw_model'].Part(dimensionality=THREE_D, name='plate', type=
    DEFORMABLE_BODY)
mdb.models['guw_model'].parts['plate'].BaseSolidExtrude(depth=0.003, sketch=
    mdb.models['guw_model'].sketches['__profile__'])
mdb.models['guw_model'].parts['plate'].DatumPlaneByPrincipalPlane(offset=0.003, 
    principalPlane=XYPLANE)
mdb.models['guw_model'].parts['plate'].DatumAxisByTwoPoint(point1=(0, 0, 0.003)
    , point2=(0, 1, 0.003))
mdb.models['guw_model'].parts['plate'].DatumAxisByTwoPoint(point1=(0, 0, 0), 
    point2=(0, 0, 0.003))
mdb.models['guw_model'].parts['plate'].Set(cells=
    mdb.models['guw_model'].parts['plate'].cells, name='plate')
mdb.models['guw_model'].parts['plate'].Set(cells=
    mdb.models['guw_model'].parts['plate'].cells, faces=
    mdb.models['guw_model'].parts['plate'].faces, name='plate-material')
mdb.models['guw_model'].parts['plate'].Set(faces=
    mdb.models['guw_model'].parts['plate'].faces.getSequenceFromMask(mask=(
    '[#10 ]', ), ), name='plate-top-surface')
mdb.models['guw_model'].parts['plate'].Set(faces=
    mdb.models['guw_model'].parts['plate'].faces.getSequenceFromMask(mask=(
    '[#10 ]', ), ), name='plate-field-output')
mdb.models['guw_model'].ConstrainedSketch(name='__profile__', sheetSize=2.0)
mdb.models['guw_model'].sketches['__profile__'].rectangle(point1=(0, 0), 
    point2=(0.5, 0.5))
mdb.models['guw_model'].Part(dimensionality=TWO_D_PLANAR, name=
    'reference_plate', type=DEFORMABLE_BODY)
mdb.models['guw_model'].parts['reference_plate'].BaseShell(sketch=
    mdb.models['guw_model'].sketches['__profile__'])
mdb.models['guw_model'].parts['reference_plate'].setMeshControls(regions=
    mdb.models['guw_model'].parts['reference_plate'].cells, technique=
    STRUCTURED)
mdb.models['guw_model'].parts['reference_plate'].seedPart(deviationFactor=0.1, 
    minSizeFactor=0.1, size=0.0037426261599909985)
mdb.models['guw_model'].parts['reference_plate'].generateMesh()
mdb.models['guw_model'].ConstrainedSketch(gridSpacing=0.08, name='__profile__', 
    sheetSize=3.25, transform=
    mdb.models['guw_model'].parts['plate'].MakeSketchTransform(
    sketchPlane=mdb.models['guw_model'].parts['plate'].datums[2], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['guw_model'].parts['plate'].datums[3], 
    sketchOrientation=RIGHT, origin=(0.0, 0.0, 0.0)))
mdb.models['guw_model'].sketches['__profile__'].CircleByCenterPerimeter(center=
    (0.02, 0.025), point1=(0.025, 0.025))
mdb.models['guw_model'].parts['plate'].CutExtrude(flipExtrudeDirection=OFF, 
    sketch=mdb.models['guw_model'].sketches['__profile__'], sketchOrientation=
    RIGHT, sketchPlane=mdb.models['guw_model'].parts['plate'].datums[2], 
    sketchPlaneSide=SIDE1, sketchUpEdge=
    mdb.models['guw_model'].parts['plate'].datums[3])
del mdb.models['guw_model'].sketches['__profile__']
mdb.models['guw_model'].ConstrainedSketch(gridSpacing=0.08, name='__profile__', 
    sheetSize=3.25, transform=
    mdb.models['guw_model'].parts['plate'].MakeSketchTransform(
    sketchPlane=mdb.models['guw_model'].parts['plate'].datums[2], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['guw_model'].parts['plate'].datums[3], 
    sketchOrientation=RIGHT, origin=(0.0, 0.0, 0.0)))
mdb.models['guw_model'].sketches['__profile__'].rectangle(point1=(
    0.00746268639340997, 0.0111940298229456), point2=(0.0335820913314819, 
    0.0373134315013885))
mdb.models['guw_model'].parts['plate'].PartitionFaceBySketch(faces=
    mdb.models['guw_model'].parts['plate'].faces[5], sketch=
    mdb.models['guw_model'].sketches['__profile__'])
mdb.models['guw_model'].parts['plate'].PartitionCellByExtrudeEdge(cells=
    mdb.models['guw_model'].parts['plate'].cells.getSequenceFromMask(mask=(
    '[#1 ]', ), ), edges=[mdb.models['guw_model'].parts['plate'].edges[4], 
    mdb.models['guw_model'].parts['plate'].edges[5], 
    mdb.models['guw_model'].parts['plate'].edges[6], 
    mdb.models['guw_model'].parts['plate'].edges[7]], line=
    mdb.models['guw_model'].parts['plate'].datums[4], sense=REVERSE)
mdb.models['guw_model'].parts['plate'].Set(faces=
    mdb.models['guw_model'].parts['plate'].faces.getSequenceFromMask(mask=(
    '[#20 ]', ), ), name='plate-top-surface')
mdb.models['guw_model'].parts['plate'].Set(cells=
    mdb.models['guw_model'].parts['plate'].cells.getSequenceFromMask(mask=(
    '[#2 ]', ), ), name='hole_01_bound_box')
mdb.models['guw_model'].parts['plate'].SetByBoolean(name='plate', operation=
    DIFFERENCE, sets=[mdb.models['guw_model'].parts['plate'].sets['plate'], 
    mdb.models['guw_model'].parts['plate'].sets['hole_01_bound_box']])
mdb.models['guw_model'].ConstrainedSketch(gridSpacing=0.04, name='__profile__', 
    sheetSize=1.84, transform=
    mdb.models['guw_model'].parts['plate'].MakeSketchTransform(
    sketchPlane=mdb.models['guw_model'].parts['plate'].datums[2], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['guw_model'].parts['plate'].datums[3], 
    sketchOrientation=RIGHT, origin=(0.0, 0.0, 0.0)))
mdb.models['guw_model'].parts['plate'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['guw_model'].sketches['__profile__'])
mdb.models['guw_model'].sketches['__profile__'].Line(point1=(
    0.00746268639340997, 0.0261194035410881), point2=(0.015, 0.025))
mdb.models['guw_model'].sketches['__profile__'].Line(point1=(0.025, 0.025), 
    point2=(0.0335820913314819, 0.0261194035410881))
mdb.models['guw_model'].sketches['__profile__'].Line(point1=(
    0.0186567157506943, 0.0111940298229456), point2=(0.02, 0.02))
mdb.models['guw_model'].sketches['__profile__'].Line(point1=(0.02, 0.03), 
    point2=(0.0186567157506943, 0.0373134315013885))
mdb.models['guw_model'].parts['plate'].PartitionFaceBySketch(faces=
    mdb.models['guw_model'].parts['plate'].faces.getSequenceFromMask(mask=(
    '[#800 ]', ), ), sketch=mdb.models['guw_model'].sketches['__profile__'], 
    sketchUpEdge=mdb.models['guw_model'].parts['plate'].datums[3])
del mdb.models['guw_model'].sketches['__profile__']
mdb.models['guw_model'].parts['plate'].PartitionCellByExtrudeEdge(cells=
    mdb.models['guw_model'].parts['plate'].cells.getSequenceFromMask(mask=(
    '[#2 ]', ), ), edges=[mdb.models['guw_model'].parts['plate'].edges[0], 
    mdb.models['guw_model'].parts['plate'].edges[1], 
    mdb.models['guw_model'].parts['plate'].edges[2], 
    mdb.models['guw_model'].parts['plate'].edges[3], 
    mdb.models['guw_model'].parts['plate'].edges[4]], line=
    mdb.models['guw_model'].parts['plate'].datums[4], sense=REVERSE)
mdb.models['guw_model'].parts['plate'].PartitionCellByExtrudeEdge(cells=
    mdb.models['guw_model'].parts['plate'].cells.getSequenceFromMask(mask=(
    '[#5 ]', ), ), edges=[mdb.models['guw_model'].parts['plate'].edges[6], 
    mdb.models['guw_model'].parts['plate'].edges[16], 
    mdb.models['guw_model'].parts['plate'].edges[22], 
    mdb.models['guw_model'].parts['plate'].edges[23], 
    mdb.models['guw_model'].parts['plate'].edges[24]], line=
    mdb.models['guw_model'].parts['plate'].datums[4], sense=REVERSE)
mdb.models['guw_model'].parts['plate'].PartitionCellByExtrudeEdge(cells=
    mdb.models['guw_model'].parts['plate'].cells.getSequenceFromMask(mask=(
    '[#b ]', ), ), edges=[mdb.models['guw_model'].parts['plate'].edges[2], 
    mdb.models['guw_model'].parts['plate'].edges[12], 
    mdb.models['guw_model'].parts['plate'].edges[33], 
    mdb.models['guw_model'].parts['plate'].edges[36], 
    mdb.models['guw_model'].parts['plate'].edges[37]], line=
    mdb.models['guw_model'].parts['plate'].datums[4], sense=REVERSE)
mdb.models['guw_model'].ConstrainedSketch(gridSpacing=0.08, name='__profile__', 
    sheetSize=3.25, transform=
    mdb.models['guw_model'].parts['plate'].MakeSketchTransform(
    sketchPlane=mdb.models['guw_model'].parts['plate'].datums[2], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['guw_model'].parts['plate'].datums[3], 
    sketchOrientation=RIGHT, origin=(0.0, 0.0, 0.0)))
mdb.models['guw_model'].sketches['__profile__'].rectangle(point1=(0.25, 
    0.242537319660187), point2=(0.268656730651855, 0.257462680339813))
mdb.models['guw_model'].parts['plate'].PartitionFaceBySketch(faces=
    mdb.models['guw_model'].parts['plate'].faces[22], sketch=
    mdb.models['guw_model'].sketches['__profile__'])
mdb.models['guw_model'].parts['plate'].PartitionCellByExtrudeEdge(cells=
    mdb.models['guw_model'].parts['plate'].cells.getSequenceFromMask(mask=(
    '[#8 ]', ), ), edges=[mdb.models['guw_model'].parts['plate'].edges[12], 
    mdb.models['guw_model'].parts['plate'].edges[13], 
    mdb.models['guw_model'].parts['plate'].edges[14], 
    mdb.models['guw_model'].parts['plate'].edges[15]], line=
    mdb.models['guw_model'].parts['plate'].datums[4], sense=REVERSE)
mdb.models['guw_model'].parts['plate'].Set(faces=
    mdb.models['guw_model'].parts['plate'].faces.getSequenceFromMask(mask=(
    '[#20 ]', ), ), name='plate-top-surface')
mdb.models['guw_model'].parts['plate'].Set(cells=
    mdb.models['guw_model'].parts['plate'].cells.getSequenceFromMask(mask=(
    '[#10 ]', ), ), name='transducer_01_bound_box')
mdb.models['guw_model'].parts['plate'].SetByBoolean(name='plate', operation=
    DIFFERENCE, sets=[mdb.models['guw_model'].parts['plate'].sets['plate'], 
    mdb.models['guw_model'].parts['plate'].sets['transducer_01_bound_box']])
mdb.models['guw_model'].ConstrainedSketch(gridSpacing=0.08, name='__profile__', 
    sheetSize=3.25, transform=
    mdb.models['guw_model'].parts['plate'].MakeSketchTransform(
    sketchPlane=mdb.models['guw_model'].parts['plate'].datums[2], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['guw_model'].parts['plate'].datums[3], 
    sketchOrientation=RIGHT, origin=(0.0, 0.0, 0.0)))
mdb.models['guw_model'].sketches['__profile__'].Line(point1=(0.25, 0.25), 
    point2=(0.26, 0.25))
mdb.models['guw_model'].sketches['__profile__'].Line(point1=(0.26, 0.25), 
    point2=(0.268656730651855, 0.25))
mdb.models['guw_model'].sketches['__profile__'].Line(point1=(0.26119402050972, 
    0.242537319660187), point2=(0.26, 0.25))
mdb.models['guw_model'].sketches['__profile__'].Line(point1=(0.26, 0.25), 
    point2=(0.26119402050972, 0.257462680339813))
mdb.models['guw_model'].parts['plate'].PartitionFaceBySketchThruAll(faces=
    mdb.models['guw_model'].parts['plate'].faces.getSequenceFromMask(mask=(
    '[#10000000 ]', ), ), sketch=
    mdb.models['guw_model'].sketches['__profile__'], sketchPlane=
    mdb.models['guw_model'].parts['plate'].datums[2], sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['guw_model'].parts['plate'].datums[3])
mdb.models['guw_model'].parts['plate'].Set(name='transducer_01', vertices=
    mdb.models['guw_model'].parts['plate'].vertices.getSequenceFromMask(mask=(
    '[#1 ]', ), ))
mdb.models['guw_model'].ConstrainedSketch(gridSpacing=0.08, name='__profile__', 
    sheetSize=3.25, transform=
    mdb.models['guw_model'].parts['plate'].MakeSketchTransform(
    sketchPlane=mdb.models['guw_model'].parts['plate'].datums[2], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['guw_model'].parts['plate'].datums[3], 
    sketchOrientation=RIGHT, origin=(0.0, 0.0, 0.0)))
mdb.models['guw_model'].sketches['__profile__'].rectangle(point1=(
    0.231343284249306, 0.242537319660187), point2=(0.25, 0.257462680339813))
mdb.models['guw_model'].parts['plate'].PartitionFaceBySketch(faces=
    mdb.models['guw_model'].parts['plate'].faces[8], sketch=
    mdb.models['guw_model'].sketches['__profile__'])
mdb.models['guw_model'].parts['plate'].PartitionCellByExtrudeEdge(cells=
    mdb.models['guw_model'].parts['plate'].cells.getSequenceFromMask(mask=(
    '[#1 ]', ), ), edges=[mdb.models['guw_model'].parts['plate'].edges[0], 
    mdb.models['guw_model'].parts['plate'].edges[1], 
    mdb.models['guw_model'].parts['plate'].edges[2], 
    mdb.models['guw_model'].parts['plate'].edges[6]], line=
    mdb.models['guw_model'].parts['plate'].datums[4], sense=REVERSE)
mdb.models['guw_model'].parts['plate'].Set(faces=
    mdb.models['guw_model'].parts['plate'].faces.getSequenceFromMask(mask=(
    '[#20 ]', ), ), name='plate-top-surface')
mdb.models['guw_model'].parts['plate'].Set(cells=
    mdb.models['guw_model'].parts['plate'].cells.getSequenceFromMask(mask=(
    '[#2 ]', ), ), name='transducer_02_bound_box')
mdb.models['guw_model'].parts['plate'].SetByBoolean(name='plate', operation=
    DIFFERENCE, sets=[mdb.models['guw_model'].parts['plate'].sets['plate'], 
    mdb.models['guw_model'].parts['plate'].sets['transducer_02_bound_box']])
mdb.models['guw_model'].ConstrainedSketch(gridSpacing=0.08, name='__profile__', 
    sheetSize=3.25, transform=
    mdb.models['guw_model'].parts['plate'].MakeSketchTransform(
    sketchPlane=mdb.models['guw_model'].parts['plate'].datums[2], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['guw_model'].parts['plate'].datums[3], 
    sketchOrientation=RIGHT, origin=(0.0, 0.0, 0.0)))
mdb.models['guw_model'].sketches['__profile__'].Line(point1=(0.231343284249306, 
    0.25), point2=(0.24, 0.25))
mdb.models['guw_model'].sketches['__profile__'].Line(point1=(0.24, 0.25), 
    point2=(0.25, 0.25))
mdb.models['guw_model'].sketches['__profile__'].Line(point1=(0.238805964589119, 
    0.242537319660187), point2=(0.24, 0.25))
mdb.models['guw_model'].sketches['__profile__'].Line(point1=(0.24, 0.25), 
    point2=(0.238805964589119, 0.257462680339813))
mdb.models['guw_model'].parts['plate'].PartitionFaceBySketchThruAll(faces=
    mdb.models['guw_model'].parts['plate'].faces.getSequenceFromMask(mask=(
    '[#20 ]', ), ), sketch=mdb.models['guw_model'].sketches['__profile__'], 
    sketchPlane=mdb.models['guw_model'].parts['plate'].datums[2], 
    sketchPlaneSide=SIDE1, sketchUpEdge=
    mdb.models['guw_model'].parts['plate'].datums[3])
mdb.models['guw_model'].parts['plate'].Set(name='transducer_02', vertices=
    mdb.models['guw_model'].parts['plate'].vertices.getSequenceFromMask(mask=(
    '[#1 ]', ), ))
mdb.models['guw_model'].ConstrainedSketch(gridSpacing=0.08, name='__profile__', 
    sheetSize=3.25, transform=
    mdb.models['guw_model'].parts['plate'].MakeSketchTransform(
    sketchPlane=mdb.models['guw_model'].parts['plate'].datums[2], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['guw_model'].parts['plate'].datums[3], 
    sketchOrientation=RIGHT, origin=(0.0, 0.0, 0.0)))
mdb.models['guw_model'].parts['plate'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['guw_model'].sketches['__profile__'])
mdb.models['guw_model'].sketches['__profile__'].rectangle(point1=(0, 
    0.257462680339813), point2=(0.5, 0.5))
mdb.models['guw_model'].ConstrainedSketch(gridSpacing=0.08, name='__profile__', 
    sheetSize=3.25, transform=
    mdb.models['guw_model'].parts['plate'].MakeSketchTransform(
    sketchPlane=mdb.models['guw_model'].parts['plate'].datums[2], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['guw_model'].parts['plate'].datums[3], 
    sketchOrientation=RIGHT, origin=(0.0, 0.0, 0.0)))
mdb.models['guw_model'].parts['plate'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['guw_model'].sketches['__profile__'])
mdb.models['guw_model'].sketches['__profile__'].rectangle(point1=(
    0.0335820913314819, 0), point2=(0.5, 0.242537319660187))
mdb.models['guw_model'].ConstrainedSketch(gridSpacing=0.08, name='__profile__', 
    sheetSize=3.25, transform=
    mdb.models['guw_model'].parts['plate'].MakeSketchTransform(
    sketchPlane=mdb.models['guw_model'].parts['plate'].datums[2], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['guw_model'].parts['plate'].datums[3], 
    sketchOrientation=RIGHT, origin=(0.0, 0.0, 0.0)))
mdb.models['guw_model'].parts['plate'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['guw_model'].sketches['__profile__'])
mdb.models['guw_model'].sketches['__profile__'].rectangle(point1=(0, 
    0.0373134315013885), point2=(0.0335820913314819, 0.257462680339813))
mdb.models['guw_model'].ConstrainedSketch(gridSpacing=0.08, name='__profile__', 
    sheetSize=3.25, transform=
    mdb.models['guw_model'].parts['plate'].MakeSketchTransform(
    sketchPlane=mdb.models['guw_model'].parts['plate'].datums[2], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['guw_model'].parts['plate'].datums[3], 
    sketchOrientation=RIGHT, origin=(0.0, 0.0, 0.0)))
mdb.models['guw_model'].parts['plate'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['guw_model'].sketches['__profile__'])
mdb.models['guw_model'].sketches['__profile__'].rectangle(point1=(
    0.268656730651855, 0.242537319660187), point2=(0.5, 0.257462680339813))
mdb.models['guw_model'].ConstrainedSketch(gridSpacing=0.08, name='__profile__', 
    sheetSize=3.25, transform=
    mdb.models['guw_model'].parts['plate'].MakeSketchTransform(
    sketchPlane=mdb.models['guw_model'].parts['plate'].datums[2], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['guw_model'].parts['plate'].datums[3], 
    sketchOrientation=RIGHT, origin=(0.0, 0.0, 0.0)))
mdb.models['guw_model'].parts['plate'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['guw_model'].sketches['__profile__'])
mdb.models['guw_model'].sketches['__profile__'].rectangle(point1=(
    0.0335820913314819, 0.242537319660187), point2=(0.231343284249306, 
    0.257462680339813))
mdb.models['guw_model'].ConstrainedSketch(gridSpacing=0.08, name='__profile__', 
    sheetSize=3.25, transform=
    mdb.models['guw_model'].parts['plate'].MakeSketchTransform(
    sketchPlane=mdb.models['guw_model'].parts['plate'].datums[2], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['guw_model'].parts['plate'].datums[3], 
    sketchOrientation=RIGHT, origin=(0.0, 0.0, 0.0)))
mdb.models['guw_model'].parts['plate'].projectReferencesOntoSketch(filter=
    COPLANAR_EDGES, sketch=mdb.models['guw_model'].sketches['__profile__'])
mdb.models['guw_model'].sketches['__profile__'].rectangle(point1=(0, 0), 
    point2=(0.0335820913314819, 0.0111940298229456))
mdb.models['guw_model'].Material(name='AluminumAlloy1100')
mdb.models['guw_model'].materials['AluminumAlloy1100'].Density(table=((2710.0, 
    ), ))
mdb.models['guw_model'].materials['AluminumAlloy1100'].Elastic(table=((
    69000000000.0, 0.33), ))
mdb.models['guw_model'].HomogeneousSolidSection(material='AluminumAlloy1100', 
    name='plate-material_continuum_section_homogenous_AluminumAlloy1100', 
    thickness=None)
mdb.models['guw_model'].parts['plate'].SectionAssignment(offset=0.0, 
    offsetField='', offsetType=MIDDLE_SURFACE, region=
    mdb.models['guw_model'].parts['plate'].sets['plate-material'], sectionName=
    'plate-material_continuum_section_homogenous_AluminumAlloy1100', 
    thicknessAssignment=FROM_SECTION)
mdb.models['guw_model'].parts['plate'].setMeshControls(regions=
    mdb.models['guw_model'].parts['plate'].cells.getSequenceFromMask(mask=(
    '[#1 ]', ), ), technique=STRUCTURED)
#* Error: Some regions cannot be Mapped.
